server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: ApiGateway
  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
    routes:
      - id: greeting
        uri: lb://SPRING-CLOUD-EUREKA-CLIENT
        predicates:
          - Path=/greeting/***